# golangci-lint v2.1.6 minimal configuration
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - ineffassign  
    - staticcheck
    - unused
  disable:
    - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0