name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no publish)'
        required: false
        default: 'true'
        type: boolean
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean ${{ github.event.inputs.dry_run == 'true' && '--snapshot --skip=publish' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
